[package]
name = "ex_determine_filesize"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
adk-rust = { workspace = true, features = ["openai"] }
dotenv = "0.15.0"
tokio = { workspace = true, features = ["full"] }
aat-fs = { workspace = true }
